#!/nix/store/rnkas52f8868g1hjdlldbvh6snm3pglv-bash-5.2-p15/bin/bash
bspc monitor 'DP-1' -d 'I' 'II' 'III' 'IV' 'V'
bspc monitor 'DP-2' -d 'I' 'II' 'III' 'IV' 'V'
bspc monitor 'eDP-1' -d 'I' 'II' 'III' 'IV' 'V'

bspc config 'active_border_color' '#145f9d'
bspc config 'border_width' '5'
bspc config 'borderless_monocle' 'on'
bspc config 'click_to_focus' 'on'
bspc config 'focus_follows_pointer' 'off'
bspc config 'focused_border_color' '#145f9d'
bspc config 'gapless_monocle' 'on'
bspc config 'merge_overlapping_monitors' 'on'
bspc config 'normal_border_color' ''
bspc config 'remove_disabled_monitors' 'on'
bspc config 'remove_unplugged_monitors' 'on'
bspc config 'split_ratio' '0.500000'
bspc config 'window_gap' '12'

bspc rule -r '*'
bspc rule -a 'quake' 'center=on' 'rectangle=2560x1600+0+0' 'state=floating'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating


/nix/store/8m6jhrr2w9b5y2l1ppwr3gpdf7dj5dn2-feh-3.9/bin/feh --bg-scale ~/.config/bspwm/wallpaper.png &
/nix/store/bm88mamr5fix1hidjlxlk40phwcw5b1k-polybar-3.6.3/bin/polybar main &

