plugin:
  dive:
    shortCut: d
    confirm: false
    description: "Dive image"
    scopes:
      - containers
    command: dive
    background: false
    args:
      - $COL-IMAGE
  move-down:
    shortCut: n
    confirm: false
    description: "Move down"
    scopes:
      - all
    command: xdotool
    background: true
    args:
      - key
      - j
