# do not add newline at begin of prompt
add_newline = true
# use all extensions
format = """
$battery\
$memory_usage\
$shlvl\
$custom\
$time\
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_status\
$kubernetes\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$lua\
$php\
$purescript\
$python\
$ruby\
$crystal\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$aws\
$gcloud\
$openstack\
$env_var\
$cmd_duration\
$jobs\
[\ue0bc](fg:237)\
$line_break\
$directory\
$status\
$character"""

[battery]
full_symbol = "\uf578"
charging_symbol = "\uf586"
discharging_symbol = "\uf57b"
format = "([ $symbol$percentage ](bg:237 $style))"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[memory_usage]
disabled = false
threshold = 75
symbol = "\uf85a"
style = "bold dimmed white"
format = "[ $symbol ${ram} ](bg:237 $style)[ \u2571](bg:237)"

[shlvl]
disabled = false
format = "[ \uf149$shlvl](bg:237 $style)[ \u2571](bg:237)"
style = "bold red"
threshold = 2

[custom.shell]
shell = "bash"
command = "echo $SHELL"
when = """ ! [[ "$SHELL" =~ "zsh" ]] """
format = "[  ](bg:237)[$output](bg:237 $style)[ \u2571](bg:237)"
style = "dimmed red"

[time]
disabled = false
format = "[ 🕙](bg:237)[$time](bg:237 $style)[ \u2571](bg:237)"
time_format = "%T"
utc_time_offset = "-5"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[ $user ](bg:237 $style)[\u2571](bg:237)"
disabled = false
# show_always = true

[hostname]
format =  "[ @$hostname ](bg:237 $style)[\u2571](bg:237)"
trim_at = "."
style = "bold red"

[git_branch]
symbol = " "
format = "[ $symbol$branch ](bg:237 $style)"
style = "bold green"
truncation_length = 18

[git_commit]
commit_hash_length = 4
tag_symbol = " "
format = "[\\($hash\\)](bg:237 $style)[ \\($tag\\)](bg:237 $style)"

[git_state]
format = '\([$state( $progress_current/$progress_total) ](bg:237 $style)\)'

[git_status]
format = "([\uf104$all_status$ahead_behind\uf105](bg:237 $style))"
style = "bold red"

[kubernetes]
disabled = false
format = "[\u2571 ](bg:237)[$context $symbol $namespace ](bg:237 $style)"
style = "blue dimmed bold"
symbol = "\ufd31"
# [kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"

[docker_context]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$context ](bg:237$style)"

[package]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[golang]
symbol = "ﳑ "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[lua]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[nim]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[java]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[rust]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[python]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[perl]
symbol = " "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

[helm]
symbol = "ﴱ "
format = "[\u2571 ](bg:237)[$symbol$version ](bg:237 $style)"

# TODO(@jakob): add langs here

[cmd_duration]
min_time = 500
show_milliseconds = false
format = "[\u2571 ](bg:237)[took](bg:237 dimmed)[ $duration ](bg:237 $style)"
style = "bold yellow"
# show_notification = true
# min_time_to_notify = 10_000


# NOTE(@jakob): new line from here on

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "\uf023"
format = "([$read_only]($read_only_style) )[$path]($style) "

[status]
symbol = ""
format = '\[[$symbol](red) [$status](bold dimmed)\] '
disabled = false
