.\" Manpage for drawio.
.\" Contact beckmann_jakob@hotmail.fr to correct errors or typos.
.TH drawio 1 "08 Aug 2020" "1.0" "drawio man page"
.SH NAME
ytp \- Draw.io offline client.
.SH SYNOPSIS
.B drawio
.SH DESCRIPTION
.B drawio
is a small script to launch an offline client of draw.io.
.SH OPTIONS
.B drawio
does not take any options.
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Jakob Beckmann (beckmann_jakob@hotmail.fr)
.\" vim: ft=nroff
