#!/usr/bin/env sh

set -e

# Command to copy to clipboard
COPY="xsel -bi"
NAME="$1"

# Get list of all logins as json
logins="$(bw list items)"
# Grab the name of every login and pip them into fzf
if [ -n "$NAME" ]; then
  name="$(echo $logins | jq -r '.[].name' | grep "$NAME")"
else
  name="$(echo $logins | jq -r '.[].name' | fzf)"
fi
# Find the login with the selected name (as a json)
selected="$(echo $logins | jq -r ".[] | select(.name == \"$name\")")"
if [ -n "$NAME" ]; then
  echo $selected | jq -r '.login.password'
  exit 0
fi

# Print the name of the selected login
echo "Name: $(echo $selected | jq -r '.name')"
echo "> Copying Username"
# Copy the username to the clipboard
printf '%s' "$(echo $selected | jq -r '.login.username')" | $COPY
echo "Press any key to copy password..."
# Wait for user input before coping the password
read
echo "> Copying Password"
# Copy the password to the clipboard
printf '%s' "$(echo $selected | jq -r '.login.password')" | $COPY

