#!/usr/bin/env sh

set -e

# Command to copy to clipboard
COPY="xsel -bi"
NAME="$1"

# Get list of all logins as json
# Grab the name of every login and pip them into fzf
if [ -n "$NAME" ]; then
  name="$(rbw list | grep "$NAME")"
else
  name="$(rbw list | fzf)"
fi

if [ -n "$NAME" ]; then
  rbw get $name
  exit 0
fi

# Print the name of the selected login
echo -e "Entry:\n $(rbw get --full $name)"
echo "> Copying Password to clipboard"
# Copy the password to the clipboard
printf '%s' "$(rbw get $name)" | $COPY

